title: 내 블로그
description: 여기는 내 간단한 블로그입니다.
baseurl: "" # 기본값, 커스텀 도메인 사용 시 설정
url: "https://hojoonsong.github.io/hojoonSong/" # GitHub Pages URL로 변경
theme: jekyll-theme-cayman

# GitHub Pages가 자동으로 처리하는 플러그인 사용
plugins:
  - jekyll-feed

# 기본 색상 설정 (선택 사항)
# 아래 항목들은 필요에 따라 추가하거나 제거할 수 있습니다.
# 색상을 변경하고 싶다면 여기서 설정할 수 있습니다.
# 별도의 CSS 파일 없이 테마의 기본 설정을 따릅니다.
