title: 내 블로그
description: 설명을 입력하세요.

remote_theme: kitian616/jekyll-TeXt-theme@2.2.6

plugins:
  - jekyll-feed
  - jekyll-paginate

sass:
  sass_dir: /tmp/jekyll-remote-theme-*/_sass

text_skin: dark # 기본 제공 다크 스킨
header:
  theme: auto
footer:
  theme: dark
