name: Update README with Language Stats

on:
  schedule:
    # 매일 자정(UTC 기준)에 워크플로우를 실행합니다.
    - cron: '45 03 * * *'
  workflow_dispatch:
    # 이 옵션은 GitHub UI를 통해 워크플로우를 수동으로 트리거할 수 있게 해줍니다.

permissions:
  contents: write
  # 필요한 API 토큰 권한을 설정합니다.

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false # 이 옵션은 작업 중에 credentials이 저장되지 않도록 합니다.

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch Language Data and Update README
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python .github/scripts/update_readme.py

    # README.md 파일을 커밋하고 푸시합니다.
    - name: Commit and Push changes
      run: |
        git config --global user.name 'your-github-username'
        git config --global user.email 'your-email@example.com'
        git add README.md
        git commit -m "Updated README with the latest language statistics"
        # main 브랜치에만 커밋하려면 아래의 '--set-upstream origin main'을 사용합니다.
        git push
